version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: containers/app.Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - ./:/src:ro
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
volumes:
  postgres_data: